version: "3.8"

services:
  api:
    image: dw-queue-api:latest
    container_name: dwqueue-api
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=DWQueueDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dwqueue-sql
    environment:
      SA_PASSWORD: "123321Aa!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: